<?php

namespace Database\Seeders;

use App\Models\Machine;
use Illuminate\Database\Seeder;

class MachineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $machines = [
            ['line_id' => 1, 'machine_name' => 'GRAFIR CR.SIZE'],
            ['line_id' => 1, 'machine_name' => 'IAM 008'],
            ['line_id' => 1, 'machine_name' => 'IAT 033'],
            ['line_id' => 1, 'machine_name' => 'IAT 034'],
            ['line_id' => 1, 'machine_name' => 'IBR 018'],
            ['line_id' => 1, 'machine_name' => 'IBR 019'],
            ['line_id' => 1, 'machine_name' => 'IBR 022'],
            ['line_id' => 1, 'machine_name' => 'IBR 024'],
            ['line_id' => 1, 'machine_name' => 'IBR 025'],
            ['line_id' => 1, 'machine_name' => 'IBR 026'],
            ['line_id' => 1, 'machine_name' => 'IBR 027'],
            ['line_id' => 1, 'machine_name' => 'IBR 028'],
            ['line_id' => 1, 'machine_name' => 'IBR 029'],
            ['line_id' => 1, 'machine_name' => 'IDR 044'],
            ['line_id' => 1, 'machine_name' => 'IDR 045'],
            ['line_id' => 1, 'machine_name' => 'IDR 046'],
            ['line_id' => 1, 'machine_name' => 'IDR 047'],
            ['line_id' => 1, 'machine_name' => 'IDR 048'],
            ['line_id' => 1, 'machine_name' => 'IDR 049'],
            ['line_id' => 1, 'machine_name' => 'IDR 050'],
            ['line_id' => 1, 'machine_name' => 'IDR 051'],
            ['line_id' => 1, 'machine_name' => 'IDR 052'],
            ['line_id' => 1, 'machine_name' => 'IDR 053'],
            ['line_id' => 1, 'machine_name' => 'IDR 054'],
            ['line_id' => 1, 'machine_name' => 'IDR 055'],
            ['line_id' => 1, 'machine_name' => 'IDR 056'],
            ['line_id' => 1, 'machine_name' => 'IDR 057'],
            ['line_id' => 1, 'machine_name' => 'IDR 058'],
            ['line_id' => 1, 'machine_name' => 'IDR 059'],
            ['line_id' => 1, 'machine_name' => 'IDR 060'],
            ['line_id' => 1, 'machine_name' => 'IDR 061'],
            ['line_id' => 1, 'machine_name' => 'IDR 062'],
            ['line_id' => 1, 'machine_name' => 'IDR 065'],
            ['line_id' => 1, 'machine_name' => 'IDR 066'],
            ['line_id' => 1, 'machine_name' => 'IDR 067'],
            ['line_id' => 1, 'machine_name' => 'IDR 068'],
            ['line_id' => 1, 'machine_name' => 'IDR 069'],
            ['line_id' => 1, 'machine_name' => 'IGR 023'],
            ['line_id' => 1, 'machine_name' => 'IGR 045'],
            ['line_id' => 1, 'machine_name' => 'IGR 046'],
            ['line_id' => 1, 'machine_name' => 'IMI 033'],
            ['line_id' => 1, 'machine_name' => 'IMI 034'],
            ['line_id' => 1, 'machine_name' => 'IMI 035'],
            ['line_id' => 1, 'machine_name' => 'IMI 036'],
            ['line_id' => 1, 'machine_name' => 'IMI 037'],
            ['line_id' => 1, 'machine_name' => 'ISP 097'],
            ['line_id' => 1, 'machine_name' => 'IMI 039'],
            ['line_id' => 1, 'machine_name' => 'IMI 045'],
            ['line_id' => 1, 'machine_name' => 'IMI 046'],
            ['line_id' => 1, 'machine_name' => 'IMM 014'],
            ['line_id' => 1, 'machine_name' => 'IMM 015'],
            ['line_id' => 1, 'machine_name' => 'ISP 074'],
            ['line_id' => 1, 'machine_name' => 'ISP 075'],
            ['line_id' => 1, 'machine_name' => 'ISP 076'],
            ['line_id' => 1, 'machine_name' => 'ISP 077'],
            ['line_id' => 1, 'machine_name' => 'ISP 078'],
            ['line_id' => 1, 'machine_name' => 'ISP 079'],
            ['line_id' => 1, 'machine_name' => 'ISP 080'],
            ['line_id' => 1, 'machine_name' => 'ISP 081'],
            ['line_id' => 1, 'machine_name' => 'ISP 082'],
            ['line_id' => 1, 'machine_name' => 'ISP 083'],
            ['line_id' => 1, 'machine_name' => 'ISP 084'],
            ['line_id' => 1, 'machine_name' => 'ISP 085'],
            ['line_id' => 1, 'machine_name' => 'ISP 086'],
            ['line_id' => 1, 'machine_name' => 'ISP 087'],
            ['line_id' => 1, 'machine_name' => 'ISP 088'],
            ['line_id' => 1, 'machine_name' => 'ISP 089'],
            ['line_id' => 1, 'machine_name' => 'ISP 095'],
            ['line_id' => 1, 'machine_name' => 'ISP 096'],
            ['line_id' => 1, 'machine_name' => 'ISP 098'],
            ['line_id' => 1, 'machine_name' => 'ISPS 027'],
            ['line_id' => 1, 'machine_name' => 'ISPS 028'],
            ['line_id' => 1, 'machine_name' => 'ISPS 029'],
            ['line_id' => 1, 'machine_name' => 'ISPS 030'],
            ['line_id' => 1, 'machine_name' => 'ISPS 031'],
            ['line_id' => 1, 'machine_name' => 'ISPS 032'],
            ['line_id' => 1, 'machine_name' => 'ISPS 033'],
            ['line_id' => 1, 'machine_name' => 'ISPS 036'],
            ['line_id' => 1, 'machine_name' => 'ISPS 037'],
            ['line_id' => 1, 'machine_name' => 'ITP 004'],
            ['line_id' => 1, 'machine_name' => 'ITP 005'],
            ['line_id' => 1, 'machine_name' => 'ITS 015'],
            ['line_id' => 1, 'machine_name' => 'ITS 016'],
            ['line_id' => 1, 'machine_name' => 'ITS 033'],
            ['line_id' => 1, 'machine_name' => 'IWB 026'],
            ['line_id' => 1, 'machine_name' => 'IWB 032'],
            ['line_id' => 1, 'machine_name' => 'IWB 033'],
            ['line_id' => 1, 'machine_name' => 'LASER MARKING CB'],
            ['line_id' => 2, 'machine_name' => 'IAT 001'],
            ['line_id' => 2, 'machine_name' => 'IAT 002'],
            ['line_id' => 2, 'machine_name' => 'IAT 003'],
            ['line_id' => 2, 'machine_name' => 'IDR 040'],
            ['line_id' => 2, 'machine_name' => 'IMI 040'],
            ['line_id' => 2, 'machine_name' => 'ISP 026'],
            ['line_id' => 2, 'machine_name' => 'ISP 027'],
            ['line_id' => 2, 'machine_name' => 'ISP 028'],
            ['line_id' => 2, 'machine_name' => 'ISP 029'],
            ['line_id' => 2, 'machine_name' => 'ISP 030'],
            ['line_id' => 2, 'machine_name' => 'ISP 031'],
            ['line_id' => 2, 'machine_name' => 'ISP 032'],
            ['line_id' => 2, 'machine_name' => 'ISP 033'],
            ['line_id' => 2, 'machine_name' => 'ISP 034'],
            ['line_id' => 2, 'machine_name' => 'ISP 035'],
            ['line_id' => 2, 'machine_name' => 'ISP 036'],
            ['line_id' => 2, 'machine_name' => 'ISP 037'],
            ['line_id' => 2, 'machine_name' => 'ISP 038'],
            ['line_id' => 2, 'machine_name' => 'ISP 039'],
            ['line_id' => 2, 'machine_name' => 'ISP 040'],
            ['line_id' => 2, 'machine_name' => 'ISP 041'],
            ['line_id' => 2, 'machine_name' => 'ISP 042'],
            ['line_id' => 2, 'machine_name' => 'ISP 043'],
            ['line_id' => 2, 'machine_name' => 'ISP 045'],
            ['line_id' => 2, 'machine_name' => 'ISP 046'],
            ['line_id' => 2, 'machine_name' => 'ISP 047'],
            ['line_id' => 2, 'machine_name' => 'ISP 048'],
            ['line_id' => 2, 'machine_name' => 'ISP 049'],
            ['line_id' => 2, 'machine_name' => 'ISP 050'],
            ['line_id' => 2, 'machine_name' => 'ISP 051'],
            ['line_id' => 2, 'machine_name' => 'ISP 052'],
            ['line_id' => 2, 'machine_name' => 'ISP 053'],
            ['line_id' => 2, 'machine_name' => 'ISP 090'],
            ['line_id' => 2, 'machine_name' => 'ISP 091'],
            ['line_id' => 2, 'machine_name' => 'ISP 093'],
            ['line_id' => 2, 'machine_name' => 'ISP 094'],
            ['line_id' => 2, 'machine_name' => 'ISP 099'],
            ['line_id' => 2, 'machine_name' => 'ISPS 001'],
            ['line_id' => 2, 'machine_name' => 'ISPS 002'],
            ['line_id' => 2, 'machine_name' => 'ISPS 003'],
            ['line_id' => 2, 'machine_name' => 'ISPS 004'],
            ['line_id' => 2, 'machine_name' => 'ISPS 005'],
            ['line_id' => 2, 'machine_name' => 'ISPS 006'],
            ['line_id' => 2, 'machine_name' => 'ISPS 007'],
            ['line_id' => 2, 'machine_name' => 'ISPS 008'],
            ['line_id' => 2, 'machine_name' => 'ISPS 009'],
            ['line_id' => 2, 'machine_name' => 'ISPS 010'],
            ['line_id' => 2, 'machine_name' => 'ISPS 011'],
            ['line_id' => 2, 'machine_name' => 'ISPS 012'],
            ['line_id' => 2, 'machine_name' => 'ISPS 013'],
            ['line_id' => 2, 'machine_name' => 'ISPS 014'],
            ['line_id' => 2, 'machine_name' => 'ISPS 015'],
            ['line_id' => 2, 'machine_name' => 'ISPS 016'],
            ['line_id' => 2, 'machine_name' => 'ISPS 017'],
            ['line_id' => 2, 'machine_name' => 'ISPS 018'],
            ['line_id' => 2, 'machine_name' => 'ISPS 019'],
            ['line_id' => 2, 'machine_name' => 'ISPS 020'],
            ['line_id' => 2, 'machine_name' => 'ISPS 021'],
            ['line_id' => 2, 'machine_name' => 'ISPS 022'],
            ['line_id' => 2, 'machine_name' => 'ISPS 023'],
            ['line_id' => 2, 'machine_name' => 'ISPS 024'],
            ['line_id' => 2, 'machine_name' => 'ISPS 025'],
            ['line_id' => 2, 'machine_name' => 'ISPS 026'],
            ['line_id' => 2, 'machine_name' => 'ISPS 034'],
            ['line_id' => 2, 'machine_name' => 'ISPS 035'],
            ['line_id' => 2, 'machine_name' => 'ITS 013'],
            ['line_id' => 2, 'machine_name' => 'ITS 014'],
            ['line_id' => 2, 'machine_name' => 'IWB 022'],
            ['line_id' => 2, 'machine_name' => 'IWB 015'],
            ['line_id' => 2, 'machine_name' => 'IWBS 001'],
            ['line_id' => 2, 'machine_name' => 'LASER MARKING CH'],
            ['line_id' => 3, 'machine_name' => 'ITS 017'],
            ['line_id' => 3, 'machine_name' => 'ILA 003'],
            ['line_id' => 3, 'machine_name' => 'ILA 004'],
            ['line_id' => 3, 'machine_name' => 'IMI 041'],
            ['line_id' => 3, 'machine_name' => 'IZY 018'],
            ['line_id' => 3, 'machine_name' => 'ILS 022'],
            ['line_id' => 3, 'machine_name' => 'IMI 042'],
            ['line_id' => 3, 'machine_name' => 'IMI 043'],
            ['line_id' => 3, 'machine_name' => 'IZY 019'],
            ['line_id' => 3, 'machine_name' => 'ISP 054'],
            ['line_id' => 3, 'machine_name' => 'ISP 055'],
            ['line_id' => 3, 'machine_name' => 'ISP 056'],
            ['line_id' => 3, 'machine_name' => 'ISP 057'],
            ['line_id' => 3, 'machine_name' => 'IWB 027'],
            ['line_id' => 3, 'machine_name' => 'IMIH 014'],
            ['line_id' => 3, 'machine_name' => 'ISP 063'],
            ['line_id' => 3, 'machine_name' => 'ISP 064'],
            ['line_id' => 3, 'machine_name' => 'ISP 065'],
            ['line_id' => 3, 'machine_name' => 'ISP 066'],
            ['line_id' => 3, 'machine_name' => 'ISP 067'],
            ['line_id' => 3, 'machine_name' => 'ISP 060'],
            ['line_id' => 3, 'machine_name' => 'ISP 068'],
            ['line_id' => 3, 'machine_name' => 'ILS 023'],
            ['line_id' => 3, 'machine_name' => 'ILA 005'],
            ['line_id' => 3, 'machine_name' => 'IZK 033'],
            ['line_id' => 3, 'machine_name' => 'IWB 028'],
            ['line_id' => 3, 'machine_name' => 'IGR 037'],
            ['line_id' => 3, 'machine_name' => 'IGR 024'],
            ['line_id' => 3, 'machine_name' => 'IGR 025'],
            ['line_id' => 3, 'machine_name' => 'IGR 026'],
            ['line_id' => 3, 'machine_name' => 'IGR 038'],
            ['line_id' => 3, 'machine_name' => 'IGR 028'],
            ['line_id' => 3, 'machine_name' => 'IGR 029'],
            ['line_id' => 3, 'machine_name' => 'IMI 044'],
            ['line_id' => 3, 'machine_name' => 'ITS 019'],
            ['line_id' => 3, 'machine_name' => 'ILP 003'],
            ['line_id' => 3, 'machine_name' => 'IZY 020'],
            ['line_id' => 3, 'machine_name' => 'IWB 029'],
            ['line_id' => 3, 'machine_name' => 'IAT 004'],
            ['line_id' => 3, 'machine_name' => 'LASER MARKING CS'],
            ['line_id' => 3, 'machine_name' => 'GRAFIR FINISH'],
            ['line_id' => 4, 'machine_name' => 'ICE 002'],
            ['line_id' => 4, 'machine_name' => 'IGR 032'],
            ['line_id' => 4, 'machine_name' => 'IGR 034'],
            ['line_id' => 4, 'machine_name' => 'IGR 039'],
            ['line_id' => 4, 'machine_name' => 'IGR 040'],
            ['line_id' => 4, 'machine_name' => 'IGR 041'],
            ['line_id' => 4, 'machine_name' => 'IGR 042'],
            ['line_id' => 4, 'machine_name' => 'IGR 043'],
            ['line_id' => 4, 'machine_name' => 'IGR 044'],
            ['line_id' => 4, 'machine_name' => 'IMIH 003'],
            ['line_id' => 4, 'machine_name' => 'ISP 069'],
            ['line_id' => 4, 'machine_name' => 'ISP 070'],
            ['line_id' => 4, 'machine_name' => 'ISP 071'],
            ['line_id' => 4, 'machine_name' => 'ISP 072'],
            ['line_id' => 4, 'machine_name' => 'ISP 073'],
            ['line_id' => 4, 'machine_name' => 'ISP 095A'],
            ['line_id' => 4, 'machine_name' => 'ISP 096B'],
            ['line_id' => 4, 'machine_name' => 'ILA 006'],
            ['line_id' => 4, 'machine_name' => 'ILA 007'],
            ['line_id' => 4, 'machine_name' => 'ILP 004'],
            ['line_id' => 4, 'machine_name' => 'IWB 030'],
            ['line_id' => 4, 'machine_name' => 'ILA 008'],
            ['line_id' => 4, 'machine_name' => 'Press Pin'],
            ['line_id' => 4, 'machine_name' => 'IZK 050'],
            ['line_id' => 4, 'machine_name' => 'IZK 051'],
            ['line_id' => 4, 'machine_name' => 'LASER MARKING CAM'],
            ['line_id' => 5, 'machine_name' => 'Hoist No.6'],
            ['line_id' => 5, 'machine_name' => 'Hoist No.7'],
            ['line_id' => 5, 'machine_name' => 'IAM 003'],
            ['line_id' => 5, 'machine_name' => 'IAM 004'],
            ['line_id' => 5, 'machine_name' => 'IAM 005'],
            ['line_id' => 5, 'machine_name' => 'IAM 007'],
            ['line_id' => 5, 'machine_name' => 'IAM 009'],
            ['line_id' => 5, 'machine_name' => 'ICK 3-1-1'],
            ['line_id' => 5, 'machine_name' => 'ICK 3-1-2'],
            ['line_id' => 5, 'machine_name' => 'ITS 020'],
            ['line_id' => 5, 'machine_name' => 'ITS 021'],
            ['line_id' => 5, 'machine_name' => 'ITS 023'],
            ['line_id' => 5, 'machine_name' => 'ITS 024'],
            ['line_id' => 5, 'machine_name' => 'ITS 025'],
            ['line_id' => 5, 'machine_name' => 'ITS 026'],
            ['line_id' => 5, 'machine_name' => 'ITS 028'],
            ['line_id' => 5, 'machine_name' => 'ITS 029'],
            ['line_id' => 5, 'machine_name' => 'ITS 030'],
            ['line_id' => 5, 'machine_name' => 'ITS 031'],
            ['line_id' => 5, 'machine_name' => 'ITS 032'],
            ['line_id' => 5, 'machine_name' => 'IZK 021'],
            ['line_id' => 5, 'machine_name' => 'IZK 038'],
            ['line_id' => 5, 'machine_name' => 'IZK 039'],
            ['line_id' => 5, 'machine_name' => 'IZK 040'],
            ['line_id' => 5, 'machine_name' => 'IZK 041'],
            ['line_id' => 5, 'machine_name' => 'IZK 041A'],
            ['line_id' => 5, 'machine_name' => 'IZK 042'],
            ['line_id' => 5, 'machine_name' => 'IZK 043'],
            ['line_id' => 5, 'machine_name' => 'IZK 044'],
            ['line_id' => 5, 'machine_name' => 'IZK 045'],
            ['line_id' => 5, 'machine_name' => 'IZK 046'],
            ['line_id' => 5, 'machine_name' => 'IZY 023'],
            ['line_id' => 5, 'machine_name' => 'IZY 024'],
            ['line_id' => 5, 'machine_name' => 'IZY 027'],
            ['line_id' => 5, 'machine_name' => 'IZY 028'],
            ['line_id' => 5, 'machine_name' => 'IZY 029'],
            ['line_id' => 5, 'machine_name' => 'IZY 030'],
            ['line_id' => 5, 'machine_name' => 'IZY 031'],
            ['line_id' => 5, 'machine_name' => 'IZYL 001'],
            ['line_id' => 5, 'machine_name' => 'IZYL 003'],
            ['line_id' => 5, 'machine_name' => 'IAM-011'],
            ['line_id' => 5, 'machine_name' => 'IAM-012'],
            ['line_id' => 5, 'machine_name' => 'IAM-013'],
            ['line_id' => 5, 'machine_name' => 'IAM-014'],
            ['line_id' => 5, 'machine_name' => 'IAM-015'],
            ['line_id' => 5, 'machine_name' => 'AAM-105'],
        ];

        foreach ($machines as $machine) {
            Machine::create($machine);
        }
    }
}

